sonar.projectKey=frontend-chinito-import
sonar.projectName=frontend-chinito-import
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/main.ts,**/main.server.ts,**/polyfills.ts,**/environments/**
sonar.javascript.lcov.reportPaths=coverage/ng-menu-dashboard/lcov.info
